### ISSUE TITLE
Refactor CLI out into franklin-cli

### ISSUE THREAD

**Issue by icaraps** [adobe-rnd/franklin#69]
This is my thinking:
* we create a new package eg franklin-cli
* we move dev/build code in there
* we create a new aio generator for franklin added as a dep to the franklin-cli see https://github.com/adobe/aio-cli-plugin-app-templates
* (optionally we publish the template once ready)
* we add the franklin-cli as a dep to the test-project and as a peerDep to franklinjs/react

then any dev/build command uses the franklin-cli package

**Comment by ramboz** [comment]
Sounds good to me.

I would also add that:
- we should separate the build and deploy steps for aio actions in franklin build and franklin deploy respectively
- we should incorporate https://github.com/adobe-rnd/franklin/blob/main/packages/gh-action-cdn-warmup/lib/gh-action-cdn-warmup.js in the deploy command
- we should add a franklin undeploy that covers https://github.com/adobe-rnd/franklin/blob/main/packages/gh-action-undeploy/lib/gh-action-undeploy.js and also undeploys the temp aio actions

**Comment by hannessolo** [comment]
Things to consider:

- The build code is specific to the framework at the moment, so franklin-cli will have build code for every framework? Will we need to provide a way so users only get the cli for the framework they want?
- Not very related but this is what got me to mentioning refactoring in the first place: While refactoring it might also make sense to think about where to move utility type files like this https://github.com/adobe-rnd/franklin/blob/override-ssr-pages/packages/franklinjs-react/route/dynamic-routes.js

**Comment by ramboz** [comment]
Maybe franklin-build could just call `npm run build` and the aio app build on the project, and we implement additionally the custom build logic for our stuff. That way, like for the tests, it's open for customers to adjust.

At some point we can even extend the app.config.yml with custom commands for build, test, deploy, etc.

**Comment by hannessolo** [comment]
Is anyone working on this yet? Otherwise I will start by creating a new package in the repository.

For the structure, which makes more sense:
a) A package like franklinjs-react-cli, and we add one for every framework we support
b) A package like franklin-cli, and the CLI includes support for every framework
c) A package like franklin-cli, and more sub-folders with more packages for every framework

**Comment by hannessolo** [comment]
For c) I would create a new separate npm module for each framework, so only the needed on can be installed. For b) it would be just one npm module that installs all the code for all frameworks

**Comment by icaraps** [comment]
Another option would be to consider the default one the react one that we currently have, and then build others later to support other frameworks if required WDYT ?.

**Comment by hannessolo** [comment]
In that case I'll make `franklin-cli` and we can decide how to support others later.
